USE adlister;
TRUNCATE user;
TRUNCATE ads;
TRUNCATE categories;
TRUNCATE ads_categories;

CREATE TABLE user(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  phone BIGINT(10) NOT NULL,
  PRIMARY KEY (id)
);
-- --
-- --
CREATE TABLE categories(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
--
CREATE TABLE ads(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  price INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id)
  REFERENCES user (id)
);

CREATE TABLE ads_categories(
  ads_id INT UNSIGNED DEFAULT NULL,
  categories_id INT UNSIGNED DEFAULT NULL,
  FOREIGN KEY (ads_id)
    REFERENCES ads(id),
  FOREIGN KEY (categories_id)
    REFERENCES categories(id)
);
